### PR TITLE
Revised descriptions on armors

### PR DESCRIPTION
**Pull request by matoge**
Revised armor descriptions. 

The main change is in how the damage is mitigated. It looked not updated (or just not correct) from the older version. 
Also, a small update is done for smoke pops, shields, and temperature descriptions.

### CODE REVIEW

**Comment by NM-Grack** [comment]
Thank you for revises because it's hard to notice where I forgot to update.
There are problems with the following points, so please modify them. 

- Line break and open one line (\n,\n\n) are deleted (However, it is very easy to read that "Up on taking damage, first ..." and "The remaining armor rating is ..." are combined into one sentence, so I think it's good as it is.)
- Forget the translation ("\n    - If the random number is greater than the armor rating, the armor has no effect.")
- There are two places where "、" is used
- Use of " - "

About use of " - ":
Spaces used in Japanese sentences will almost certainly cause line breaks at that point.
RimWorld has a function to adjust so that line breaks don't occur in the middle of English words, but this function has the problem that it is not possible to distinguish between Japanese and English.
For example, the sentence 「例えば このような一文があるとします」 is mistakenly determined to consist of "very long two words" of 例えば and このような一文があるとします. 
Therefore, using spaces in sentences requires writing a line feed character (\n, half-width space, etc.) at the position where you want to start a new line.

For lines where "\n    - " is used, there is a revision proposal that inserts a half-width space for line breaks at any place, so please refer to it if you like. 

Proposal: \n\n    - もしこのランダムな数字がアーマー値の半分よりも小さい 場合,攻撃は完全に無効になります.\n    - この数字が半分よりも大きく,アーマー値以下の場合,ダメージ は半減され,打撲系のダメージになります.\n    - この数字がアーマー値を上回る場合,アーマーは効果を発揮 しません.

**Comment by NM-Grack** [comment]
Sorry, "\n - " means \n____-_.
"_" is a half-width space.

**Comment by NM-Grack** [comment]
Sorry, "\n - " means \n〇〇〇〇-〇.
"〇" is a half-width space.

**Comment by NM-Grack** [comment]
I'm glad your cooperation with the translation work, but I ended up making various requests to you. I'm sorry if it makes you feel burdened.
I've committed the revised, so please check if you want.

I would be grateful if you could continue to help with the translation work!

**Comment by NM-Grack** [comment]
I'm glad your cooperation with the translation work, but I ended up making various requests to you.
I'm sorry if it makes you feel burdened.
I've committed the revised, so please check if you want.

I would be grateful if you could continue to help with the translation work!

**Comment by matoge** [comment]
@NM-Grack 
Thanks for revising. I've been kind of busy and missed your comments. 

Yeah, I understood the effect of using spaces in the middle of Japanese sentences. I'll mind it in the future commit.

I didn't understand why space is added for example in "小さい 場合," ?
I guess it is not automatically line breaking.. meaning it is very difficult to write a long line without carefully adding spaces. Correct?

I am now kind of revising backstories so I want to know what is the good numbers..

**Comment by NM-Grack** [comment]
I relieve to find that you didn't feel burdened.

This description field can only display up to "〇〇〇〇-〇もしこのランダムな数字がアーマー値の半分よりも小さい" on one line, so the space for line breaks is added in "小さい 場合,". (〇 is a space)
I check the position of the space for line breaks by reflecting it on the game screen.

It is best not to display spaces in the text, but if necessary, backstories can display up to 19 characters (38 bytes) in one line.
Also, even if one line is a little short, it will be easier to read if you start a new line at the phrase break. For example, "小さい 場合" instead of "小さい場 合".

**Pull request merged**
